apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.usePopulator: 'true'
  name: catalogue-db-dbdata
spec:
  preallocation: false
  source:
    blank: {}
  storage:
    resources:
      requests:
        storage: 10Gi
    storageClassName: ocs-external-storagecluster-ceph-rbd
    
---
    
    # Service 配置
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
spec:
  selector:
    app/name: catalogue-db  # Service 选择器，与 Pod 的标签匹配
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306  # 目标容器端口
  type: ClusterIP  # 内部通信类型
  
---
  
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: catalogue-db
  annotations:
    description: db
  labels:
    app: database
    os.template.kubevirt.io/fedora: 'true'
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        app/name: catalogue-db
        kubevirt.io/domain: example
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            - disk:
                bus: virtio
              name: dbdata
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: q35
        memory:
          guest: 4Gi
      hostname: catalogue-db
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              packages:
                - mariadb-server
              runcmd:
                - setenforce 0
                - systemctl stop firewalld
                - mkfs -t btrfs /dev/vdc
                - mount /dev/vdc /var/lib/mysql
                - chown mysql:mysql -R /var/lib/mysql
                - systemctl enable mariadb
                - systemctl start mariadb
                - mysql -e "CREATE DATABASE socksdb;"
                - mysql -e "CREATE USER 'root'@'%' IDENTIFIED BY 'admin';"
                - mysql -e "GRANT ALL PRIVILEGES ON socksdb.* TO 'root'@'%';"
                - mysql -e "FLUSH PRIVILEGES;"
                - mysql -e "USE socksdb; CREATE TABLE test (id INT PRIMARY KEY,name VARCHAR(255) NOT NULL,text VARCHAR(255) NOT NULL);"
                - curl -o dump.sql https://raw.githubusercontent.com/microservices-demo/catalogue/refs/heads/master/docker/catalogue-db/data/dump.sql
                - mysql -h localhost -u root socksdb < dump.sql
              ssh_pwauth: true
              chpasswd:
              user: root
              password: password
              chpasswd: { expire: False }
          name: cloudinitdisk
        - dataVolume:
            name: catalogue-db-dbdata
          name: dbdata
